// Generated by gencpp from file mpu/angles.msg
// DO NOT EDIT!


#ifndef MPU_MESSAGE_ANGLES_H
#define MPU_MESSAGE_ANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mpu
{
template <class ContainerAllocator>
struct angles_
{
  typedef angles_<ContainerAllocator> Type;

  angles_()
    : angleX(0)
    , angleY(0)
    , angleZ(0)  {
    }
  angles_(const ContainerAllocator& _alloc)
    : angleX(0)
    , angleY(0)
    , angleZ(0)  {
  (void)_alloc;
    }



   typedef int16_t _angleX_type;
  _angleX_type angleX;

   typedef int16_t _angleY_type;
  _angleY_type angleY;

   typedef int16_t _angleZ_type;
  _angleZ_type angleZ;





  typedef boost::shared_ptr< ::mpu::angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpu::angles_<ContainerAllocator> const> ConstPtr;

}; // struct angles_

typedef ::mpu::angles_<std::allocator<void> > angles;

typedef boost::shared_ptr< ::mpu::angles > anglesPtr;
typedef boost::shared_ptr< ::mpu::angles const> anglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpu::angles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpu::angles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mpu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mpu': ['/home/ubuntu/Desktop/Exo_workspace/src/mpu/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mpu::angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpu::angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpu::angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpu::angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpu::angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpu::angles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpu::angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76513374ad214381430fd6261a078518";
  }

  static const char* value(const ::mpu::angles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76513374ad214381ULL;
  static const uint64_t static_value2 = 0x430fd6261a078518ULL;
};

template<class ContainerAllocator>
struct DataType< ::mpu::angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpu/angles";
  }

  static const char* value(const ::mpu::angles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpu::angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 angleX\n\
int16 angleY\n\
int16 angleZ\n\
";
  }

  static const char* value(const ::mpu::angles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpu::angles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angleX);
      stream.next(m.angleY);
      stream.next(m.angleZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpu::angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpu::angles_<ContainerAllocator>& v)
  {
    s << indent << "angleX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.angleX);
    s << indent << "angleY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.angleY);
    s << indent << "angleZ: ";
    Printer<int16_t>::stream(s, indent + "  ", v.angleZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPU_MESSAGE_ANGLES_H
